apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
# storing the data in a Secret component doesn't automatically make it secure.
# there are built-in mechanism (like encrytion) for basic security, which are not enabled by default.
data:
    # bash
    mongo-root-username: dXNlcm5hbWU=    # echo -n 'username' | base64
    mongo-root-password: cGFzc3dvcmQ=    # echo -n 'password' | base64
